version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      JWT_ALG: HS256
      JWT_SECRET_KEY: SuperS3cr3t!
      JWT_ACCESS_EXP: 360
      JWT_REFRESH_EXP: 720
  redis:
    image: "redis:7.2.5-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: